# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.loopsystems.ca:
  peer1.loopsystems.ca:
  peer0.sender.com:
  peer1.sender.com:

networks:
  loopNetw:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - loopNetw

  peer0.loopsystems.ca:
    container_name: peer0.loopsystems.ca
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.loopsystems.ca
    networks:
      - loopNetw

  peer1.loopsystems.ca:
    container_name: peer1.loopsystems.ca
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.loopsystems.ca
    networks:
      - loopNetw

  peer0.sender.com:
    container_name: peer0.sender.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.sender.com
    networks:
      - loopNetw

  peer1.sender.com:
    container_name: peer1.sender.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.sender.com
    networks:
      - loopNetw

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.loopsystems.ca:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/loopsystems.ca/peers/peer0.loopsystems.ca/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/loopsystems.ca/peers/peer0.loopsystems.ca/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/loopsystems.ca/peers/peer0.loopsystems.ca/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/loopsystems.ca/users/Admin@loopsystems.ca/msp

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.loopsystems.ca
      - peer1.loopsystems.ca
      - peer0.sender.com
      - peer1.sender.com
    networks:
      - loopNetw
